### ISSUE TITLE
QEMU doesn't word

### ISSUE THREAD

**Issue by Lr-2002** [kamaboko123/30daysOS#4]
hello ,delighted to see your source code on linux 
It helps a lot.
But ,while using the ```make run ``` in day03' harib00a
It was stuck by such command
1. booting from hard disk
 failed :not read the boot disk
2. booting from floppy 

I don't know the reason
Maybe it should be done using a new USB?
Could it run on your PC using command ' make run '?

this is my config of my PC
1. ubuntu 20.04 LTS 64 bits  (for this one ,i've tried to solve by change the QEMU = x86_64)
2. AMD 4800H
3. SSD as the hard disk

**Comment by kamaboko123** [comment]
Thank you for your report.

It is expected behavior that from harib00a to harib00g are seemingly not working.
it is specified in the Book(30日でできる！ OS自作入門) page 48 - 59.(especially page 53 about harib00a)

Error message(`failed :not read the boot disk`)  is caused by priority of boot device.
Hariboite OS is made as image for floppy and set to qemu.
qemu tries to boot from hard disk at first but ​hard disk is not set on qemu.
Therefor, It is expected behavior that error is occur in boot from hard disk.
Next, qemu tried to boot from floppy because qemu failed to boot hard disk.(qemu printed message `booting from floppy`)

If you don't want to see the error message(`failed :Could not read the boot disk`), We can change boot device priority.

Boot device is specified by `-boot` option.
`$(QEMU) -drive format=raw,file=$(TARGET_IMG),if=floppy -boot a`

a = floppy
c = hard disk (default)
d = cdrom

**Comment by Lr-2002** [comment]
Pleasure to get your reply.(It's like a boy with longing for his idol and get the reply)
Thanks very much!


Well, I've ever read a little of the document of QEMU .I'll try your advice latter 
Thanks again !
